### ISSUE TITLE
Naming suggestion

### ISSUE THREAD

**Issue by abea** [apostrophecms/apostrophe-media-sources#7]
## The problem to solve

The list of media sources includes "Apostrophe" for the local/primary media files. Not all users of Apostrophe will be familiar with that name, however.

## Proposed solution

I would suggest changing that default name to something like "My Library" or "Media Library" to be more generic.

**Comment by ValJed** [comment]
Yes this is a good idea, I just made the modification in my current PR, I'll close this issue when it's merged.

**Comment by ValJed** [comment]
It has been modified in `Media Library`.
